name: Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  node_ci:
    name: Node CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Verify Node version
        run: node -v

      - name: Run tests
        run: |
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No tests found — skipping"
          fi
