name: Node CI

# This controls when the workflow runs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 👈 allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]  # You can test multiple Node versions

    steps:
      # Checkout the repo code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js with the version defined above
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies using package-lock.json (faster & clean)
      - name: Install dependencies
        run: npm install

      # Optional: Build step (skip if no build script)
      - name: Build project
        run: npm run build --if-present

      # Run your Jest tests or similar
      - name: Run tests
        run: npm test
